### ISSUE TITLE
add Nengo?

### ISSUE THREAD

**Issue by NickleDave** [AidanRocke/neuromorphic_computers#1]
Thanks for putting this together.

Are you familiar with the Nengo simulator and the Neural Engineering Framework?
https://www.nengo.ai/
They have a few backends that run on neuromorphic chips.
I also highly recommend reading "How to Build a Brain" by Chris Eliasmith, the group leader. Very relevant to your interests.

Sorry if this is old news to you, just thought I'd give them a mention since I didn't see them on your list

**Comment by NickleDave** [comment]
For a more technical intro to the math side, I would read the "Neural Engineering Framework" book. I think it is one of the few attempts to integrate computational neuroscience under a single mathematical formalism, and also happens be a pretty good review of a lot of work up to ~2004.

Then you could look at theses from the group after to see where they've gone next.
http://compneuro.uwaterloo.ca/publications.html

Also they're so a great job of making their code open:
https://github.com/ctn-waterloo

**Comment by AidanRocke** [comment]
Thanks a lot. To be completely honest this isn't old news to me. All of this is new and very exciting! :) Will definitely check the theses and publications of the Eliasmith group over the weekend. Also plan to start reading the Neural Engineering Framework book soon.

**Comment by NickleDave** [comment]
Nice! Glad I could introduce you to it.

Feel free to DM me on Twitter whenever, I'm taking part in their summer school this year and will be happy to tell you about the experience
